language: c

compiler:
  - gcc

before_install:
  - 
  - 

install:
  - 


script:
  - wget https://raw.githubusercontent.com/Nax/rubynette/master/rubynette.rb
  - ruby rubynette.rb */*.c */*.h 
  - make
